id = "itzcast.applications"
name = "Applications"
version = "0.0.1"
enabled = true
command = ["@java", "-jar", "../.runtime/itzcast-extensions.jar", "applications"]
hooks = ["startup", "suggest"]
priority = 50
timeoutMs = 3000
